# Docker compose template to build in the Dockerfile in the folder and share two folders with the container


version: '1.0'
services:
  llama_api_server:
    build: ghcr.io/romainmendez/llama_api_server-cd-test:latest
    ports:
      - "5000:5000"
    volumes:
      - ./config:/home/runninguser/config
      - ./models:/home/runninguser/models
